---
all:
  children:
    web:
      hosts:
        web01:
          ansible_host: 192.168.56.11
        web02:
          ansible_host: 192.168.56.12

    database:
      hosts:
        db01:
          ansible_host: 192.168.56.31
          postgresql_node_role: primary
        db02:
          ansible_host: 192.168.56.32
          postgresql_node_role: replica

