---
- name: Validate SSH configuration
  ansible.builtin.command: /usr/sbin/sshd -t
  changed_when: false
  listen: Reload SSH

- name: Reload SSH service
  ansible.builtin.service:
    name: ssh
    state: reloaded
  listen: Reload SSH

- name: Reload nftables service
  ansible.builtin.service:
    name: nftables
    state: reloaded
  listen: Reload nftables

