---
application_port: 8080
application_database_enabled: true
application_database_host: "{{ postgresql_primary_address }}"
haproxy_port: 80

keepalived_nodes:
  web01:
    state: MASTER
    priority: 150
  web02:
    state: BACKUP
    priority: 100

